### ISSUE TITLE
这个项目不更新了吗

### ISSUE THREAD

**Issue by cloudmist** [Omooo/Android_QA#2]
最后一次更新是20年10月，是不是不更新了

**Comment by Omooo** [comment]
Sorry，接近不更新啦～因为我已经面试完啦，最新的 Readme 上面已经有把常见的面试题的回答
都整理好了～有不少同学靠这个成功上岸啦～推荐看看这个口水话哈～


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Omooo/Android_QA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 上午9:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Omooo/Android_QA] 这个项目不更新了吗 (#2)





 
最后一次更新是20年7月，是不是不更新了

**Comment by cloudmist** [comment]
好的，谢谢
